### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/eiquadprog#1]
The original mention of the license of the code is largely missing. 
The code is a copy paster or former code by Andrea.

This should be fixed before any formal release I would say.

**Comment by nim65s** [comment]
Hi,

The release v1.0.0 is imminent. The license says

> Stack Of Tasks development team

@andreadelprete: do you want to add anything ?

**Comment by jcarpent** [comment]
The original license is coming from people of Eigen. Please copy/past where it is required.

**Comment by jcarpent** [comment]
I think @jmirabel may provide some hints about the original license

**Comment by jmirabel** [comment]
Here are the pieces of information I could gather:

> About the license of quadprog, I traced back the origin of the file:
> 
> - original version: QuadProg++, MIT License,
https://github.com/liuq/QuadProgpp/ (see
https://github.com/liuq/QuadProgpp/commit/8767d072046fe5362a172313b96211f19febba53)
> 
> - first port: uQuadProg++, GPL at first but became LGPL v3 License,
http://siloe.deis.unical.it/~angelo/node/133,
https://github.com/fx74/uQuadProg
> 
> - Then, there is eiquadprog.hpp: under GPL, but the license was not
updated when uQuadProg became LGPL. The same other (Gael Guennebaud,
Eigen's leader) did the same job with QuadProg++ and the file is LGPL
(https://gitlab.inria.fr/alta/alta/blob/3c11d5a4ed6cd15ed39f938a1da1aecad1a4b31e/external/quadprog++/QuadProg++.cc)
> 
> - Finally, the version on this page, which has the same license as
eiquadprog.hpp: http://www.cs.cmu.edu/~bstephe1/
> 
> To conclude, I think we can safely assume quadprog is LGPL.

**Comment by jcarpent** [comment]
So the core code of this module should be LGPL and not BSD as currently mentioned.

**Comment by jmirabel** [comment]
I think it should be GPL, except if Gael Guennebaud (and maybe Benjamin Stephens) agrees to change this to LGPL.

**Comment by andreadelprete** [comment]
Very good job backtracking the origin of this piece of code @jmirabel !
I confirm that this matches what I knew about it, and that I started my development from the version of Benjamin Stephens.

**Comment by nim65s** [comment]
Thanks for that job :D

From the link in #2, it looks like Gael Guennebaud latest version is LGPL, so I think that we can use that.

**Comment by jmirabel** [comment]
I think you can assume Gael Guennebaud has already accepted the LGPL licence.

**Comment by gabrielebndn** [comment]
Hi everybody,
so are we going for LGPL?
Concretely, what action should we take and where should the licence info go?
Is it enough to change the [LICENSE](https://github.com/stack-of-tasks/eiquadprog/blob/master/LICENSE) file?
@jcarpent, what do you think?
@nim65s, could you take care of it?

**Comment by nim65s** [comment]
According to [GNU](https://www.gnu.org/licenses/gpl-howto.html), for the LGPL (and their other licenses), ind addition of the main file, we have to put a license notice in each and every file.

I hate that, but will do it.

**Comment by nim65s** [comment]
Fixed and released. Thank you all on this issue :)

**Comment by gabrielebndn** [comment]
Thanks @nim65s :)
