### ISSUE TITLE
Setting up a CI

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/eiquadprog#11]
As this project is used by many other programs, it would be nice to setup a CI to test at least simple programes and the installation.

Best,

Justin

**Comment by nim65s** [comment]
As every other SoT / HPP / loco-3d / Gepetto project, Gitlab-CI is working:
https://gitlab.laas.fr/stack-of-tasks/eiquadprog/pipelines

A better integration with Github repositories is coming.

**Comment by nim65s** [comment]
gitlab-ci is available, on pushes & pull requests
