### ISSUE TITLE
CMake / Compilation on Mac

### ISSUE THREAD

**Issue by jbmouret** [stack-of-tasks/eiquadprog#14]
Hi

to compile on a mac with the boost installed by brew, I had to change the CMakeList.txt (line 61-62) to add boost (since it is in /usr/loca/include and not /usr/include):

```Cmake
TARGET_INCLUDE_DIRECTORIES(${PROJECT_NAME} SYSTEM PRIVATE ${EIGEN3_INCLUDE_DIR} ${Boost_INCLUDE_DIR})
TARGET_INCLUDE_DIRECTORIES(${PROJECT_NAME} SYSTEM INTERFACE ${EIGEN3_INCLUDE_DIR} ${Boost_INCLUDE_DIR})
```

**Comment by nim65s** [comment]
Hi @jbmouret,

Thanks for this report. We are currently making many changes on the Boost detection and use part of CMake.

I guess I fixed this one in #13 : could you please try to see if the branch `release/1.2.1` works for you, without this change ?

**Comment by jbmouret** [comment]
Thanks. Yes, the release/1.2.1 works fine.

**Comment by nim65s** [comment]
This is now released, sorry for the delay.
