### ISSUE TITLE
trace solver issue

### ISSUE THREAD

**Issue by dalinel** [stack-of-tasks/eiquadprog#28]
Hi
I think there is a problem with the EIQGUADPROG_TRACE_SOLVER definition
https://github.com/stack-of-tasks/eiquadprog/blob/de8337e2491d4f23c463e9b3aad9e1c425c96461/CMakeLists.txt#L61-L64

It should be something like this right ?
```
if(TRACE_SOLVER)
   target_compile_definitions(${PROJECT_NAME} PRIVATE EIQGUADPROG_TRACE_SOLVER)
endif(TRACE_SOLVER)
```

otherwise it always trace the solver

**Comment by nim65s** [comment]
Thanks !
