### ISSUE TITLE
Document the difference between solvers

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/eiquadprog#3]
As reported by @jmirabel in https://github.com/humanoid-path-planner/hpp-core/issues/190#issuecomment-574752995, it would be nice to explain why do we have
- eiquadprog
- eiquadprog-fast
- eiquadprog-rt

This should probably go to the README.

@gabrielebndn: could you do that ? :)

**Comment by gabrielebndn** [comment]
It can be easily explained in a few lines.
I think the best would be a properly-made doc, with doxygen and all, but it would take me some time to set it up.
If I can just put them in the README, I can certainly do it very quickly.

**Comment by nim65s** [comment]
A couple lines in the README would do for now, because it currently says that

**Comment by jmirabel** [comment]
A doxygen doc is overkill for this purpose.

**Comment by nim65s** [comment]
fixed by #5
