### ISSUE TITLE
Clarification about the License of this package

### ISSUE THREAD

**Issue by pFernbach** [stack-of-tasks/eiquadprog#45]
Hello, could you please make the licensing of this package more clear ? It is containing both LGPL and GPL licenses, and I understand that it's based on previous work that was under GPL. But in the header files it is first declared as LGPL and then below GPL is mentionned. It looks like the GPL part about uquadprog only, but I would like to be sure about that. 

Thanks

**Comment by nim65s** [comment]
ref #1.

As we don't have a simple git history with authorship information, I'm not even sure how to get the information you are looking for

**Comment by nim65s** [comment]
I'll close this. Please re-open #1 and discuss there if needed.
